### ISSUE TITLE
Error and kicking players

### ISSUE THREAD

**Issue by yooniks** [Limework/RedisBungee#115]
### intended behavior

.

### what the behavior you actually saw

`[11:22:51] [RedisBungee Pool Thread #20/ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@27f0ad19, id=153438, owner=com.imaginarycode.minecraft.redisbungee.RedisBungee@4656fcc5, task=com.imaginarycode.minecraft.redisbungee.RedisBungeeListener$$Lambda$2257/0x00007f6518c8b7a0@3153ce84, delay=0, period=0, running=true) encountered an exception
java.lang.RuntimeException: java.lang.NullPointerException: null key in entry: null=d9b48645-134d-32bc-9724-a458684de32e
	at com.imaginarycode.minecraft.redisbungee.api.PlayerDataManager.serversToPlayersBuilder(PlayerDataManager.java:270) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.internal.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$3(LocalLoadingCache.java:183) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.internal.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2688) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.internal.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2686) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.internal.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2669) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.internal.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.internal.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:58) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.api.PlayerDataManager.serversToPlayers(PlayerDataManager.java:238) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.AbstractRedisBungeeAPI.getServerToPlayers(AbstractRedisBungeeAPI.java:116) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.AbstractRedisBungeeAPI.getPlayersOnServer(AbstractRedisBungeeAPI.java:126) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.RedisBungeeListener.lambda$onPluginMessage$0(RedisBungeeListener.java:97) ~[?:?]
	at net.md_5.bungee.scheduler.BungeeTask.run(Unknown Source) ~[XCord-1.61A.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:523ed61:unknown]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.NullPointerException: null key in entry: null=d9b48645-134d-32bc-9724-a458684de32e
	at com.imaginarycode.minecraft.redisbungee.internal.com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:31) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.internal.com.google.common.collect.ImmutableMultimap$Builder.put(ImmutableMultimap.java:171) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.api.PlayerDataManager$1.lambda$doPooledPipeline$0(PlayerDataManager.java:254) ~[?:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.api.PlayerDataManager$1.doPooledPipeline(PlayerDataManager.java:254) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.api.PlayerDataManager$1.doPooledPipeline(PlayerDataManager.java:243) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.api.tasks.RedisPipelineTask.unifiedJedisTask(RedisPipelineTask.java:33) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.api.tasks.RedisTask.execute(RedisTask.java:59) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.api.tasks.RedisTask.call(RedisTask.java:35) ~[?:?]
	at com.imaginarycode.minecraft.redisbungee.api.PlayerDataManager.serversToPlayersBuilder(PlayerDataManager.java:268) ~[?:?]
	... 18 more
`

### Steps to reproduce

Use latest version of ValioBungee and BungeeCord 1.21.

### Velocity or Bungeecord Versions

BungeeCord 1.21

### RedisBungee Version & Redis Version

7.2 redis version
redisbungee 0.12.4

**Comment by alaajel** [comment]
part of #117
