### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Thepaco777** [Limework/RedisBungee#116]
### intended behavior

[19:32:56 ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@5496c165, id=8869, owner=com.imaginarycode.minecraft.redisbungee.RedisBungee@514dc5f4, task=com.imaginarycode.minecraft.redisbungee.RedisBungeeListener$$Lambda$2806/0x00007f1704f78670@6aacc88f, delay=0, period=0, running=true) encountered an exception
java.lang.RuntimeException: java.lang.NullPointerException: null key in entry: null=bf20048c-a55a-322c-a100-5493e7b87286
        at com.imaginarycode.minecraft.redisbungee.api.PlayerDataManager.serversToPlayersBuilder(PlayerDataManager.java:270) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$3(LocalLoadingCache.java:183) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2688) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2686) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2669) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:58) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.api.PlayerDataManager.serversToPlayers(PlayerDataManager.java:238) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.AbstractRedisBungeeAPI.getServerToPlayers(AbstractRedisBungeeAPI.java:116) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.AbstractRedisBungeeAPI.getPlayersOnServer(AbstractRedisBungeeAPI.java:126) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.RedisBungeeListener.lambda$onPluginMessage$0(RedisBungeeListener.java:97) ~[?:?]
        at net.md_5.bungee.scheduler.BungeeTask.run(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:da542e6:unknown]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.NullPointerException: null key in entry: null=bf20048c-a55a-322c-a100-5493e7b87286
        at com.imaginarycode.minecraft.redisbungee.internal.com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:31) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.com.google.common.collect.ImmutableMultimap$Builder.put(ImmutableMultimap.java:171) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.api.PlayerDataManager$1.lambda$doPooledPipeline$0(PlayerDataManager.java:254) ~[?:?]
        at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.api.PlayerDataManager$1.doPooledPipeline(PlayerDataManager.java:254) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.api.PlayerDataManager$1.doPooledPipeline(PlayerDataManager.java:243) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.api.tasks.RedisPipelineTask.unifiedJedisTask(RedisPipelineTask.java:33) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.api.tasks.RedisTask.execute(RedisTask.java:59) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.api.tasks.RedisTask.call(RedisTask.java:35) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.api.PlayerDataManager.serversToPlayersBuilder(PlayerDataManager.java:268) ~[?:?]
        ... 18 more

### what the behavior you actually saw

errors in the console

### Steps to reproduce

the error started coming out of nowhere

### Velocity or Bungeecord Versions

last xCord

### RedisBungee Version & Redis Version

Redis Version: 7
RedisBungee Version: 0.12.4

**Comment by MassiveLag** [comment]
https://github.com/MassiveLag/ValioBungee/releases/tag/release fixed here for you.

**Comment by Thepaco777** [comment]
okay thank you very much

**Comment by alaajel** [comment]
#117
