### ISSUE TITLE
ERR wrong number of arguments for 'auth' command'

### ISSUE THREAD

**Issue by SnubSum31041247** [Limework/RedisBungee#124]
```
[17:19:59 INFO] [redisbungee]: Version: 0.12.5
[17:19:59 INFO] [redisbungee]: Loaded proxy id proxy-1
[17:19:59 INFO] [redisbungee]: Loaded network id main
[17:19:59 INFO] [redisbungee]: handle reconnect to last server: false
[17:19:59 INFO] [redisbungee]: handle motd: true
[17:19:59 INFO] [redisbungee]: RedisBungee MODE: SINGLE
[17:19:59 INFO] [redisbungee]: Compatibility JedisPool was created
[17:20:00 ERROR]: Can't create plugin redisbungee
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: JedisDataException: ERR wrong number of arguments for 'auth' command
  at RedisBungeeVelocityPlugin.<init>(RedisBungeeVelocityPlugin.java:100)
  at VelocityPluginModule.configure(VelocityPluginModule.java:47)
  while locating RedisBungeeVelocityPlugin

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
JedisDataException:        "com.imaginarycode.minecraft.redisbungee.internal.jedis.exceptions.JedisDataException"
RedisBungeeVelocityPlugin: "com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityPlugin"
VelocityPluginModule:      "com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule"
========================
End of classname legend:
========================

        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1151) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:131) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:173) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:418) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:289) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:71) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
Caused by: com.imaginarycode.minecraft.redisbungee.internal.jedis.exceptions.JedisDataException: ERR wrong number of arguments for 'auth' command
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Protocol.processError(Protocol.java:106) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Protocol.process(Protocol.java:163) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Protocol.read(Protocol.java:222) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:350) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.getStatusCodeReply(Connection.java:268) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.helloOrAuth(Connection.java:492) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.initializeFromClientConfig(Connection.java:401) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.<init>(Connection.java:67) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Jedis.<init>(Jedis.java:220) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.JedisFactory.makeObject(JedisFactory.java:170) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.create(GenericObjectPool.java:566) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:306) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:233) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.util.Pool.getResource(Pool.java:38) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.JedisPool.getResource(JedisPool.java:378) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.api.summoners.JedisPooledSummoner.<init>(JedisPooledSummoner.java:30) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.api.config.loaders.ConfigLoader.loadConfig(ConfigLoader.java:184) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityPlugin.<init>(RedisBungeeVelocityPlugin.java:106) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityPlugin$$FastClassByGuice$$195ec37.GUICE$TRAMPOLINE(<generated>) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityPlugin$$FastClassByGuice$$195ec37.apply(<generated>) ~[?:?]
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
        ... 6 more
```

**Comment by SnubSum31041247** [comment]
I'm new to it

**Comment by alaajel** [comment]
your redis server uses a password so set it in the config file, or jgive redis server version + plugin version

**Comment by SnubSum31041247** [comment]
redis:7.2.0   , plugin:RedisBungee-Proxy-Velocity-0.12.5-all

**Comment by alaajel** [comment]
whats your redis server configuration? check it please if you have set the correct password. Because error generally means something is wrong either password or somehow you have username set up and didn't set it in valiobungee config.
```yml
redis-server: 127.0.0.1
redis-port: 6379

# Cluster Mode
# enabling this option will enable cluster mode.
cluster-mode-enabled: false

# FORMAT:
# redis-cluster-servers:
# - host: 127.0.0.1`
#   port: 2020
# - host: 127.0.0.1
#   port: 2021
# - host: 127.0.0.1
#   port: 2021

# you can set single server and Jedis will automatically discover cluster nodes,
# but might fail if this single redis node is down when Proxy startup, its recommended put the all the nodes
redis-cluster-servers:
  - host: 127.0.0.1
    port: 6379

# OPTIONAL: if your redis uses acl usernames set the username here. leave empty for no username.
redis-username: "" # <--------- check this

# OPTIONAL but recommended: If your Redis server uses AUTH, set the required password.
redis-password: "" # <--------- check this
```

**Comment by SnubSum31041247** [comment]
redis-username: Redis-x64-5.0.14.1
redis-password: 123456

**Comment by alaajel** [comment]
is this `Redis-x64-5.0.14.1` username set in redis server aswell?

**Comment by SnubSum31041247** [comment]
yes

**Comment by alaajel** [comment]
i am unable to replicate this error whats over with usersnames or not. so you might wana publish your config files of the redis server and valiobungee config file and log files of the proxy.

**Comment by SnubSum31041247** [comment]
velocity\plugins\redisbungee\config.yml
```yml
# RedisBungee configuration file.
# Notice:
# Redis 7.2.4 is last free and open source Redis version after license change
# https://download.redis.io/releases/redis-7.2.4.tar.gz which you have to compile yourself,
# unless your package manager still provide it.
# Here is The alternatives
# - 'ValKey' By linux foundation https://valkey.io/download/
# - 'KeyDB' by Snapchat inc https://docs.keydb.dev/docs/download/


# The 'Redis', 'ValKey', 'KeyDB' server you will use.
# these settings are ignored when cluster mode is enabled.
redis-server: 127.0.0.1
redis-port: 6379

# Cluster Mode
# enabling this option will enable cluster mode.
cluster-mode-enabled: false

# FORMAT:
# redis-cluster-servers:
# - host: 127.0.0.1`
#   port: 2020
# - host: 127.0.0.1
#   port: 2021
# - host: 127.0.0.1
#   port: 2021

# you can set single server and Jedis will automatically discover cluster nodes,
# but might fail if this single redis node is down when Proxy startup, its recommended put the all the nodes
redis-cluster-servers:
  - host: 127.0.0.1
    port: 6379

# OPTIONAL: if your redis uses acl usernames set the username here. leave empty for no username.
redis-username: "Redis-x64-5.0.14.1"

# OPTIONAL but recommended: If your Redis server uses AUTH, set the required password.
redis-password: "123456"

# Maximum connections that will be maintained to the Redis server.
# The default is 10. This setting should be left as-is unless you have some wildly
# inefficient plugins or a lot of players.
max-redis-connections: 10

# since redis can support ssl by version 6 you can use SSL/TLS in redis bungee too!
# but there is more configuration needed to work see https://github.com/ProxioDev/RedisBungee/issues/18
# Keep note that SSL/TLS connections will decrease redis performance so use it when needed.
useSSL: false

# An identifier for this network, which helps to separate redisbungee instances on same redis instance.
# You can use environment variable 'REDISBUNGEE_NETWORK_ID' to override
network-id: "main"

# An identifier for this BungeeCord / Velocity instance. Will randomly generate if leaving it blank.
# You can set Environment variable 'REDISBUNGEE_PROXY_ID' to override
proxy-id: "proxy-1"

# since RedisBungee Internally now uses UnifiedJedis instead of Jedis, JedisPool.
# which will break compatibility with old plugins that uses RedisBungee JedisPool
# so to mitigate this issue, RedisBungee will create an JedisPool for compatibility reasons.
# disabled by default
# Automatically disabled when cluster mode is enabled
enable-jedis-pool-compatibility: false

# max connections for the compatibility pool
compatibility-max-connections: 3

# restore old login behavior before 0.9.0 update
# enabled by default
# when true: when player login and there is old player with same uuid it will get disconnected as result and new player will log in
# when false: when a player login but login will fail because old player is still connected.
kick-when-online: true

# enabled by default
# this option tells RedisBungee handle motd and set online count, when motd is requested
# you can disable this when you want to handle motd yourself, use RedisBungee api to get total players when needed :)
handle-motd: true

# A list of IP addresses for which RedisBungee will not modify the response for, useful for automatic
# restart scripts.
# Automatically disabled  if handle-motd is disabled.
exempt-ip-addresses: []

# disabled by default
# RedisBungee will attempt to connect player to last server that was stored.
reconnect-to-last-server: false

# For redis bungee legacy commands
# either can be run using '/rbl glist' for example
# or if 'install' is set to true '/glist' can be used.
# 'install' also overrides the proxy installed commands
#
# In legacy commands each command got it own permissions since they had it own permission pre new command system,
# so it's also applied to subcommands in '/rbl'.
commands:
  # Permission redisbungee.legacy.use
  redisbungee-legacy:
    enabled: false
    subcommands:
        # Permission redisbungee.command.glist
        glist:
          enabled: false
          install: false
        # Permission redisbungee.command.find
        find:
          enabled: false
          install: false
        # Permission redisbungee.command.lastseen
        lastseen:
          enabled: false
          install: false
        # Permission redisbungee.command.ip
        ip:
          enabled: false
          install: false
        # Permission redisbungee.command.pproxy
        pproxy:
          enabled: false
          install: false
        # Permission redisbungee.command.sendtoall
        sendtoall:
          enabled: false
          install: false
        # Permission redisbungee.command.serverid
        serverid:
          enabled: false
          install: false
        # Permission redisbungee.command.serverids
        serverids:
          enabled: false
          install: false
       # Permission redisbungee.command.plist
        plist:
          enabled: false
          install: false
  # Permission redisbungee.command.use
  redisbungee:
    enabled: true

# Config version DO NOT CHANGE!!!!
config-version: 2
```

**Comment by SnubSum31041247** [comment]
velocity\logs\2025-01-02-1.log.gz

**Comment by SnubSum31041247** [comment]
I didn't modify any files from the redis server，Here is the redis file I installed using it
Redis-x64-5.0.14.1.msi
resp-2022.5.zip
Whether it has anything to do with jedis or not, I don't have access to any jedis-related documents

**Comment by SnubSum31041247** [comment]
![屏幕截图 2025-01-05 121327](https://github.com/user-attachments/assets/ca1591d9-31fd-4560-9914-8463fb409daa)

**Comment by alaajel** [comment]
> redis:7.2.0 , plugin:RedisBungee-Proxy-Velocity-0.12.5-all

this is conflicting information you provided that you ran 7.2.0 redis. based on the screenshot you provided and the 'installer name'. you are running the redis port for windows but that version is 5.x something which is really old for valiobungee you need 6.2.0 or above. 

https://github.com/ProxioDev/ValioBungee/wiki/Installation#supported-redis-versions

you can use the windows subsystem for linux to run the latest version of redis or valkey if you want. https://learn.microsoft.com/en-us/windows/wsl/install

  




> ![屏幕截图 2025-01-05 121327](https://private-user-images.githubusercontent.com/174024600/400177592-ca1591d9-31fd-4560-9914-8463fb409daa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwNzgyMTUsIm5iZiI6MTczNjA3NzkxNSwicGF0aCI6Ii8xNzQwMjQ2MDAvNDAwMTc3NTkyLWNhMTU5MWQ5LTMxZmQtNDU2MC05OTE0LTg0NjNmYjQwOWRhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwNVQxMTUxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjcyYWUxNzAwN2FjZTkzYTY4YWRiMjEzYzcxMzBjNzUwMGJhNDM1MmU4YmQwYzllMDIzNjk1OWU4MzkyNjY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BO0YiJO7Y3oLwo1WekFYMGjMSBVATDBcQEL_Z4Z-IJQ)

this is not how you set the username of the redis server. you need to read documentation of redis
https://redis.io/docs/latest/
or valkey
https://valkey.io/topics/


*Valkey is fork of redis after the license change.*

**Comment by alaajel** [comment]
other note:

when you post configs or any code on github issue or comments you can use this format

![image](https://github.com/user-attachments/assets/827ea210-f562-4c7e-a157-3895a7b4d058)
which will show up like this:

```yml
#some config file 
value1: 0
```
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by SnubSum31041247** [comment]
I downloaded redis 7.2.2 and the error message has changed, what should I do? 
I downloaded "Redis-7.2.2-Windows-x64-msys2-with-Service" from https://github.com/redis-windows/redis-windows

```yml
[23:09:26 ERROR]: Can't create plugin redisbungee
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: JedisAccessControlException: WRONGPASS invalid username-password pair or user is disabled.                       <<<<----------------------------
  at RedisBungeeVelocityPlugin.<init>(RedisBungeeVelocityPlugin.java:100)
  at VelocityPluginModule.configure(VelocityPluginModule.java:47)
  while locating RedisBungeeVelocityPlugin

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
JedisAccessControlException: "com.imaginarycode.minecraft.redisbungee.internal.jedis.exceptions.JedisAccessControlException"
RedisBungeeVelocityPlugin:   "com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityPlugin"
VelocityPluginModule:        "com.velocitypowered.proxy.plugin.loader.java.VelocityPluginModule"
========================
End of classname legend:
========================

        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:251) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1151) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.createPlugin(JavaPluginLoader.java:131) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:173) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:418) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:289) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:71) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
Caused by: com.imaginarycode.minecraft.redisbungee.internal.jedis.exceptions.JedisAccessControlException: WRONGPASS invalid username-password pair or user is disabled.
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Protocol.processError(Protocol.java:104) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Protocol.process(Protocol.java:163) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Protocol.read(Protocol.java:222) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:350) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.getStatusCodeReply(Connection.java:268) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.helloOrAuth(Connection.java:492) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.initializeFromClientConfig(Connection.java:401) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.Connection.<init>(Connection.java:67) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.ConnectionFactory.makeObject(ConnectionFactory.java:59) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.create(GenericObjectPool.java:566) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:306) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.commonspool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:233) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.util.Pool.getResource(Pool.java:38) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.ConnectionPool.getResource(ConnectionPool.java:29) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.ConnectionPool.getResource(ConnectionPool.java:7) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.providers.PooledConnectionProvider.getConnection(PooledConnectionProvider.java:68) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.executors.DefaultCommandExecutor.executeCommand(DefaultCommandExecutor.java:23) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:252) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.internal.jedis.UnifiedJedis.set(UnifiedJedis.java:720) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.api.summoners.JedisPooledSummoner.<init>(JedisPooledSummoner.java:37) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.api.config.loaders.ConfigLoader.loadConfig(ConfigLoader.java:184) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityPlugin.<init>(RedisBungeeVelocityPlugin.java:106) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityPlugin$$FastClassByGuice$$1c80682.GUICE$TRAMPOLINE(<generated>) ~[?:?]
        at com.imaginarycode.minecraft.redisbungee.RedisBungeeVelocityPlugin$$FastClassByGuice$$1c80682.apply(<generated>) ~[?:?]
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148) ~[velocity-3.4.0-SNAPSHOT-455.jar:3.4.0-SNAPSHOT (git-4aa9ee77-b455)]
        ... 6 more

**Comment by SnubSum31041247** [comment]
it is my config file
```yml
# RedisBungee configuration file.
# Notice:
# Redis 7.2.4 is last free and open source Redis version after license change
# https://download.redis.io/releases/redis-7.2.4.tar.gz which you have to compile yourself,
# unless your package manager still provide it.
# Here is The alternatives
# - 'ValKey' By linux foundation https://valkey.io/download/
# - 'KeyDB' by Snapchat inc https://docs.keydb.dev/docs/download/


# The 'Redis', 'ValKey', 'KeyDB' server you will use.
# these settings are ignored when cluster mode is enabled.
redis-server: 127.0.0.1
redis-port: 6379

# Cluster Mode
# enabling this option will enable cluster mode.
cluster-mode-enabled: false

# FORMAT:
# redis-cluster-servers:
# - host: 127.0.0.1`
#   port: 2020
# - host: 127.0.0.1
#   port: 2021
# - host: 127.0.0.1
#   port: 2021

# you can set single server and Jedis will automatically discover cluster nodes,
# but might fail if this single redis node is down when Proxy startup, its recommended put the all the nodes
redis-cluster-servers:
  - host: 127.0.0.1
    port: 6379

# OPTIONAL: if your redis uses acl usernames set the username here. leave empty for no username.
redis-username: "redis-7.2.2"        <<<<------------------------------------------------------------------------

# OPTIONAL but recommended: If your Redis server uses AUTH, set the required password.
redis-password: "123456"   <<<<---------------------------------------------------------------------------

# Maximum connections that will be maintained to the Redis server.
# The default is 10. This setting should be left as-is unless you have some wildly
# inefficient plugins or a lot of players.
max-redis-connections: 10

# since redis can support ssl by version 6 you can use SSL/TLS in redis bungee too!
# but there is more configuration needed to work see https://github.com/ProxioDev/RedisBungee/issues/18
# Keep note that SSL/TLS connections will decrease redis performance so use it when needed.
useSSL: false

# An identifier for this network, which helps to separate redisbungee instances on same redis instance.
# You can use environment variable 'REDISBUNGEE_NETWORK_ID' to override
network-id: "main"

# An identifier for this BungeeCord / Velocity instance. Will randomly generate if leaving it blank.
# You can set Environment variable 'REDISBUNGEE_PROXY_ID' to override
proxy-id: "proxy-1"

# since RedisBungee Internally now uses UnifiedJedis instead of Jedis, JedisPool.
# which will break compatibility with old plugins that uses RedisBungee JedisPool
# so to mitigate this issue, RedisBungee will create an JedisPool for compatibility reasons.
# disabled by default
# Automatically disabled when cluster mode is enabled
enable-jedis-pool-compatibility: false

# max connections for the compatibility pool
compatibility-max-connections: 3

# restore old login behavior before 0.9.0 update
# enabled by default
# when true: when player login and there is old player with same uuid it will get disconnected as result and new player will log in
# when false: when a player login but login will fail because old player is still connected.
kick-when-online: true

# enabled by default
# this option tells RedisBungee handle motd and set online count, when motd is requested
# you can disable this when you want to handle motd yourself, use RedisBungee api to get total players when needed :)
handle-motd: true

# A list of IP addresses for which RedisBungee will not modify the response for, useful for automatic
# restart scripts.
# Automatically disabled  if handle-motd is disabled.
exempt-ip-addresses: []

# disabled by default
# RedisBungee will attempt to connect player to last server that was stored.
reconnect-to-last-server: false

# For redis bungee legacy commands
# either can be run using '/rbl glist' for example
# or if 'install' is set to true '/glist' can be used.
# 'install' also overrides the proxy installed commands
#
# In legacy commands each command got it own permissions since they had it own permission pre new command system,
# so it's also applied to subcommands in '/rbl'.
commands:
  # Permission redisbungee.legacy.use
  redisbungee-legacy:
    enabled: false
    subcommands:
        # Permission redisbungee.command.glist
        glist:
          enabled: false
          install: false
        # Permission redisbungee.command.find
        find:
          enabled: false
          install: false
        # Permission redisbungee.command.lastseen
        lastseen:
          enabled: false
          install: false
        # Permission redisbungee.command.ip
        ip:
          enabled: false
          install: false
        # Permission redisbungee.command.pproxy
        pproxy:
          enabled: false
          install: false
        # Permission redisbungee.command.sendtoall
        sendtoall:
          enabled: false
          install: false
        # Permission redisbungee.command.serverid
        serverid:
          enabled: false
          install: false
        # Permission redisbungee.command.serverids
        serverids:
          enabled: false
          install: false
       # Permission redisbungee.command.plist
        plist:
          enabled: false
          install: false
  # Permission redisbungee.command.use
  redisbungee:
    enabled: true

# Config version DO NOT CHANGE!!!!
config-version: 2

**Comment by alaajel** [comment]
i think you are confusing username with something else.
here is a guide about the username part
https://redis.io/docs/latest/operate/oss_and_stack/management/security/acl/

Either way. try remove username by setting it to `redis-username: ""`

**Comment by SnubSum31041247** [comment]
ok,output this information means that there is no problem?
Thanks a lot!!!

```yml
[13:18:52 INFO] [redisbungee]: Version: 0.12.5
[13:18:52 INFO] [redisbungee]: Loaded proxy id proxy-1
[13:18:52 INFO] [redisbungee]: Loaded network id main
[13:18:52 INFO] [redisbungee]: handle reconnect to last server: false
[13:18:52 INFO] [redisbungee]: handle motd: true
[13:18:52 INFO] [redisbungee]: RedisBungee MODE: SINGLE
[13:18:52 INFO] [redisbungee]: Successfully connected to Redis.
[13:18:52 INFO] [redisbungee]: Redis server version: 7.2.2
[13:18:53 INFO]: Loaded plugin redisbungee 0.12.5 by astei, ProxioDev
